version: 2
updates:
- package-ecosystem: docker
  directory: "/s6-overlay"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - jacanales
  assignees:
  - jacanales
