name: Publish Docker image DockerHub
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Github Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Pull docker image
        run: docker pull ghcr.io/jacanales/php-fpm:7.4

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: php-fpm/7.4-fpm
          platforms: linux/386
          push: true
          tags: |
            jacanales/php-fpm:7.4