name: Publish Docker image
on:
  push:
    branches: php8
jobs:
  push_to_registry:
    name: Push Docker image to Github Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GH_PACKAGES }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: php-fpm/7.4-fpm
          file: php-fpm/7.4-fpm/Dockerfile
          platforms: linux/386
          push: true
          cache-from: type=registry,ref=jacanales/php-fpm:7.4
          cache-to: type=inline
          tags: |
            jacanales/php-fpm:7.4
            ghcr.io/jacanales/php-fpm:7.4